server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    druid:
      initial-size: 1
      max-active: 3
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=utf8
    username: root
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.qiye.aliyun.com
    port: 25
    username: youEmailAddress
    password: youEmailPassword
    default-encoding: UTF-8
    from: nickname<youEmailAddress>
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
